swagger: "2.0"
info:
  description: "Marketplace"
  version: "1.0.0"
  title: "Marketplace"
basePath: "/v1"
tags:
- name: "products"
  description: "Everything about products"
- name: "shopping"
  description: "API's referring to the purchase of products"
- name: "customer"
  description: "Everything about customers"
schemes:
- "https"
- "http"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "Return all products"
      description: "Return all products"
      operationId: "listProducts"
      produces:
      - "application/json"
      parameters:
        - in: query
          name: page
          type: integer
          required: true
        - in: query
          name: size
          type: integer
          required: false
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ProductModel"
    post:
      tags:
      - "products"
      summary: "Place an new product"
      description: "Place an new product"
      operationId: "addProduct"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Place a new product"
        required: true
        schema:
          $ref: "#/definitions/ProductModel"
      responses:
        "201":
          description: "successful operation"
        "400":
          description: "Invalid product"
    put:
      tags:
      - "products"
      summary: "Update an existing product"
      description: "Update an existing product"
      operationId: "updateProduct"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Product object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/ProductModel"
      responses:
        "204":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Product not found"
  /products/{idProduct}:
    get:
      tags:
      - "products"
      summary: "Find product by id"
      description: "Find product by id"
      operationId: "findProductById"
      produces:
      - "application/json"
      parameters:
      - name: "idProduct"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProductModel"
        "404":
          description: "Order not found"
    delete:
      tags:
      - "products"
      summary: "Delete product order by ID"
      description: "Delete product order by ID"
      operationId: "deleteProduct"
      produces:
      - "application/json"
      parameters:
      - name: "idProduct"
        in: "path"
        description: "ID of product to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "204":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
  /shopping:
    post:
      tags:
      - "shopping"
      summary: "Customer buys a product"
      description: "Customer buys a product"
      operationId: "buyProduct"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Order placed for purchasing the product"
        required: true
        schema:
          $ref: "#/definitions/ShoppingProduct"
      responses:
        "201":
          description: "successful operation"
        "400":
          description: "Invalid product"
  /customer:
    post:
      tags:
      - "customer"
      summary: "Register a new customer"
      description: "Register a new customer"
      operationId: "addCustomer"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New Customer"
        required: true
        schema:
          $ref: "#/definitions/Customer"
      responses:
        "201":
          description: "successful operation"
        "400":
          description: "Invalid product"
definitions:
  ProductModel:
    type: "object"
    required:
    - name
    - categories
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
      categories:
        type: "array"
        items:
          type: "string"
  ShoppingProduct:
    type: "object"
    required:
    - id_customer
    - id_product
    properties:
      id_customer:
        type: "integer"
        format: "int64"
      id_product:
        type: "integer"
        format: "int64"
      rating:
        type: "integer"
        minimum: 0
        maximum: 5
  Customer:
    type: "object"
    required:
    - name
    properties:
      name:
        type: "string"
    