swagger: "2.0"
info:
  description: "Marketplace"
  version: "1.0.0"
  title: "Marketplace"
basePath: "/v1"
tags:
- name: "products"
  description: "Everything about products"
schemes:
- "https"
- "http"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "Return all products"
      description: "Return all products"
      operationId: "listProducts"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ProductModel"
    post:
      tags:
      - "products"
      summary: "Place an new product"
      description: "Place an new product"
      operationId: "addProduct"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "order placed for purchasing the pet"
        required: true
        schema:
          $ref: "#/definitions/ProductCreationModel"
      responses:
        "201":
          description: "successful operation"
        "400":
          description: "Invalid product"
    put:
      tags:
      - "products"
      summary: "Update an existing product"
      description: "Update an existing product"
      operationId: "updateProduct"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Product object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/ProductModel"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Product not found"
  /products/{idProduct}:
    get:
      tags:
      - "products"
      summary: "Find product by id"
      description: "Find product by id"
      operationId: "findProductById"
      produces:
      - "application/json"
      parameters:
      - name: "idProduct"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProductModel"
        "404":
          description: "Order not found"
    delete:
      tags:
      - "products"
      summary: "Delete product order by ID"
      description: "Delete product order by ID"
      operationId: "deleteProduct"
      produces:
      - "application/json"
      parameters:
      - name: "idProduct"
        in: "path"
        description: "ID of product to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
definitions:
  ProductModel:
    type: "object"
    properties:
      name:
        type: "string"
      description:
        type: "string"
  ProductCreationModel:
    type: "object"
    required:
      - categories
      - product
    properties:
      product:
        $ref: "#/definitions/ProductModel"
      categories:
        type: "array"
        items:
          type: "string"
    
      
    